### PR TITLE
Update README.md

### LINKED ISSUE #41: add readme badges
i want to add readme badges. .Please assign this issue to me under GSSOC
badges

### PR DESCRIPTION
**Pull request by S-ishita**
Closes #41 
Screenshot from 2023-05-20 21-07-50

### CODE REVIEW

**Comment by S-ishita** [comment]
I have read the Arakoo CLA Document and I hereby sign the CLA

**Comment by S-ishita** [comment]
recheck

**Comment by sandys** [comment]
@S-ishita please remove this part. we generally like to keep the repo fairly scientific in its description.

also please reduce the size of boxes by atleast 60%. this is too large. this has to be small to occupy no more than two lines. it doesnt need to be big. 
image
here's an example of how small (you can make it even smaller)

**Comment by S-ishita** [comment]
@sandys removed the first row.. I cant change the size as it is made with standard code.Also it is occupying only two lines now..hence i guess it can be merged now.Do let me know for any further changes...

**Pull request merged**
