### PR TITLE
Add parent pom and related works

### PR DESCRIPTION
**Pull request by robincakeellis**
- parent pom builds all three modules
- common dependency versions in parent
- Spring Boot 3.0.5 was the best option given the odd security configuration (breaks in later versions)
- manual test: chat app to show integration with edgechain app
- removed .DS_Store files from repo

**Note**

Shading is doing something clever to allow autoconfiguration resources to be vislble to dependent code. The resources are in `autoroute` and are essential for `flyfly` to work. Shading of `autoroute` is still required until autoconfig is investigated.

/claim #194

### CODE REVIEW

**Comment by robincakeellis** [comment]
recheck

**Comment by sandys** [comment]
hi @robincakeellis 
thanks so much for your commit. We are holding a merge for a previous merge (currently in main) that is breaking some GPT algorithm implementations.
But will merge this post that release gets fixed. 

super appreciative of your time. Spring Boot gets so much active push back from the mainstream ML community, that we feel very grateful for any help.

**Comment by sandys** [comment]
@robincakeellis what did u mean by this ? 
"Spring Boot 3.0.5 was the best option given the odd security configuration (breaks in later versions)"

we want to fix this internally since we want to upgrade to 3.1 as fast as we can.

**Comment by robincakeellis** [comment]
> 



> "Spring Boot 3.0.5 was the best option given the odd security configuration (breaks in later versions)"

Each version of Spring Boot gets more strict about allowed parameters. Your app was 3.0.0 but used webflux 3.0.5. I tried 3.1.3 but got security errors due to properties being blank or null. 3.0.10 was the same.

3.0.5 works as required and matches the dependencies you had in main

**Comment by robincakeellis** [comment]
I am Asia GMT +7 btw. Let me know if you have a Discord, or want to arrange a voice/video chat in near future.

**Comment by robincakeellis** [comment]
> does this become a single step ?

You can run `mvn` in Flyspring folder. autoroute is built followed by flyfly and finally edge app. All tests pass.

You still need to copy the app to examples folder.

**Comment by sandys** [comment]
> I am Asia GMT +7 btw. Let me know if you have a Discord, or want to arrange a voice/video chat in near future.

hi @robincakeellis how do we ping u on discord ? our server is https://discord.gg/w6c2TeJT
Wanted to chat about a possible project.

**Pull request merged**
