### PR TITLE
fix: dual-build

### PR DESCRIPTION
**Pull request by ezhil56x**
/claim #272 

- Created release-java.yml (manual trigger)
- Created release-js.yml (manual trigger)
- Made changes to pr-build (automated)

### CODE REVIEW

**Comment by ezhil56x** [comment]
I have read the Arakoo CLA Document and I hereby sign the CLA

**Comment by sandys** [comment]
@ezhil56x ur merge is on the wrong branch. this should merge on the TS branch.

the main branch doesnt even have any javascript code. how did u test this ? can u show me running actions and builds on ur repo please ? so i can verify before i merge.

**Comment by ezhil56x** [comment]
@sandys All the workflows should be run from ts branch? Should I make changes and add the workflows to the ts branch and test it once more. Correct me if I'm wrong

**Comment by sandys** [comment]
Yes. All workflows should run from ts branch.

The PR workflow should only kick in if the PR is made w.r.t ts branch. If
PR is made for main branch, then your workflows should not trigger.

However the larger question is - how did u test on main branch ? There is
no javascript code there.

I would want to see this working on ur fork before I accept the bounty.

**Comment by ezhil56x** [comment]
@sandys Closing this PR will open new one

**Pull request closed without merging**
