### PR TITLE
added: ui for hyde-search

### PR DESCRIPTION
**Pull request by Sadaf-A**

### CODE REVIEW

**Comment by sandys** [comment]
@Sadaf-A there are conflicts. please resolve

**Comment by sandys** [comment]
@Sadaf-A conflicts are still there

**Comment by Sadaf-A** [comment]
> @Sadaf-A conflicts are still there

it came after the latest commit I have resolved it now

**Comment by sandys** [comment]
@Sadaf-A u have tested this after ur fixes right ? because this will get merged for harsh and i dont want his entire code to break

**Comment by Sadaf-A** [comment]
> @Sadaf-A u have tested this after ur fixes right ? because this will get merged for harsh and i dont want his entire code to break

yes, I have tested both mine and harsh's changes

**Pull request merged**
