### PR TITLE
Added palm-2 api and have written test

### PR DESCRIPTION
**Pull request by Gmin2**
/claim #279 
/fixes #279

### CODE REVIEW

**Comment by Gmin2** [comment]
I have read the Arakoo CLA Document and I hereby sign the CLA

**Comment by sandys** [comment]
Please don't use json and read from the files.
We use jsonnet and have already built a jsonnet read utility.

Your prompts will need to be in the jsonnet format and read using the
jsonnet loader utility.

Also please fix spelling mistakes in filenames

**Comment by sandys** [comment]
You have also not created a standalone example that we will test. Please
create a working example - that will be our validation.
Make sure the prompts are according to what palm2 expects. Gpt has slightly
different format of prompts.

**Comment by Gmin2** [comment]
Hey @sandys please see this we dont need to integrate this api right?

https://generativelanguage.googleapis.com/v1beta2/models/chat-bison-001:generateMessage?key=YOUR_API_KEY

**Comment by sandys** [comment]
https://developers.generativeai.google/models/language

@Min2who text-bison-001, chat-bison-001 and embedding-gecko-001 are 3 variants of the Palm2 model.
However you can do either text-bison-001 OR chat-bison-001 for completion of this bounty.

**Comment by sandys** [comment]
@Min2who also want to point out that this PR is failing integration tests. u can see the PR Build/js target failing in the checks section above.
u can also see this https://github.com/arakoodev/EdgeChains/actions/runs/7055654590/job/19206425414?pr=285

**Pull request closed without merging**
