### PR TITLE
Robin code quality

### PR DESCRIPTION
**Pull request by robincakeellis**
Example code quality
- @`Bean` methods do not need to be public
- use template `{}` in logging instead of string concat
- use try.. with.. resources for clean closing
- unit tests for changed code
- TestContainer used to test PostgreSQL table create
- more logging to support testing/developers

### CODE REVIEW

**Comment by sandys** [comment]
hi @robincakeellis thanks for this! really appreciate your contribution.

we are waiting for our larger merge (https://github.com/arakoodev/EdgeChains/pull/205) to go through. will merge this immediately afterwards

**Comment by robincakeellis** [comment]
> we are waiting for our larger merge (#205) to go through. will merge this immediately afterwards

ok i will check again after your merge in case there are any merge issues. No rush!

**Comment by sandys** [comment]
@robincakeellis ur build has failed and i see some conflicts.

**Comment by robincakeellis** [comment]
Fixed merge issues and a new build is rolling.

**Comment by robincakeellis** [comment]
@sandys You have two maven calls in your workflow. First packages with no tests and second runs test. Please change this to one call : mvn clean package

This will prevent creating a build if the tests fail.

And if possible, set the timeout to 30 minutes. One test hangs the build for six hours if it fails.

**Pull request merged**
