### PR TITLE
Design Javascript/Typescript equivalent of the Edgechains library

### PR DESCRIPTION
**Pull request by Hrushi20**
I'm interested in working on rewriting the library into Js/Ts. I raised this Pull Request as part of Design. I've got a high level overview of Project.

Based on my understanding-
* A user hits a rest endpoint to interact with LLM.
* Edgechains parses the request, extract information, builds query using jsonnet.
* The query is forwarded to OpenAI via http and the response is returned back to the user. 

I am not sure what the postgresChain, redisChain do? 

Also, what is the final scope of the project? What kind of jsonnet files do we have to execute?

### CODE REVIEW

**Comment by Hrushi20** [comment]
I have read the Arakoo CLA Document and I hereby sign the CLA

**Comment by sandys** [comment]
@Hrushi20 thanks for your interest. the work for the TS library has already progressed quite a bit on the TS branch https://github.com/arakoodev/edgechains/tree/ts

what part are you interested in enhancing ?

**Comment by Hrushi20** [comment]
I'm open to working on any feature. I've seen the typescript library has been initialized. Based on the bounty, I'd like to work on integrating OpenAI requests using jsonnet.

**Comment by sandys** [comment]
> I'm open to working on any feature. I've seen the typescript library has been initialized. Based on the bounty, I'd like to work on integrating OpenAI requests using jsonnet.

that work has finished in the branch.

**Comment by Hrushi20** [comment]
What are the pending works left which I can contribute to?

**Pull request closed without merging**
