### PR TITLE
SocratesCoT

### PR DESCRIPTION
**Pull request by Shahil093**
Commits on Jun 9, 2023
[Socrates COT]

### CODE REVIEW

**Comment by Shahil093** [comment]
hy can u ping me on my Gmail as I dint get any dm option direct to you

**Comment by Shahil093** [comment]
I have read the Arakoo CLA Document and I hereby sign the CLA

**Comment by Shahil093** [comment]
recheck

**Comment by sandys** [comment]
closing after discussion.

**Pull request closed without merging**
